### ISSUE TITLE
Tips on converting ConLL format to TextAnnotation format from ccg_nlpy?

### ISSUE THREAD

**Issue by marvinstanley** [mayhewsw/ner-with-partial-annotations#2]
I have a document which is tagged in the ConLL format, an example of the format:
John B-PER
works O
for O
Microsoft B-ORG

Do you have any tips on how to convert this format into the TextAnnotation format from ccg_nlpy, just like the one provided in the sample data?

**Comment by mayhewsw** [comment]
[This script](https://github.com/CogComp/talen/blob/master/data/txt2tajson.py) may be useful. That only converts from text files to TextAnnotation, but it shouldn't be hard to rewrite it to accept column input.
